# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'FrmDepto.ui'
##
## Created by: Qt User Interface Compiler version 6.5.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QDateEdit, QFrame, QHeaderView,
    QLabel, QLineEdit, QMainWindow, QMenu,
    QMenuBar, QSizePolicy, QSpinBox, QStatusBar,
    QTabWidget, QTableWidget, QTableWidgetItem, QToolBar,
    QWidget)
import recursos_rc

class Ui_FrmDepto(object):
    def setupUi(self, FrmDepto):
        if not FrmDepto.objectName():
            FrmDepto.setObjectName(u"FrmDepto")
        FrmDepto.resize(624, 375)
        self.actionConex_o = QAction(FrmDepto)
        self.actionConex_o.setObjectName(u"actionConex_o")
        self.actionSair = QAction(FrmDepto)
        self.actionSair.setObjectName(u"actionSair")
        self.actionListar = QAction(FrmDepto)
        self.actionListar.setObjectName(u"actionListar")
        self.actionSair_2 = QAction(FrmDepto)
        self.actionSair_2.setObjectName(u"actionSair_2")
        self.action_Novo = QAction(FrmDepto)
        self.action_Novo.setObjectName(u"action_Novo")
        icon = QIcon()
        icon.addFile(u":/icones/botoes/Add.bmp", QSize(), QIcon.Normal, QIcon.Off)
        self.action_Novo.setIcon(icon)
        self.action_Editar = QAction(FrmDepto)
        self.action_Editar.setObjectName(u"action_Editar")
        icon1 = QIcon()
        icon1.addFile(u":/icones/botoes/COPY.BMP", QSize(), QIcon.Normal, QIcon.Off)
        self.action_Editar.setIcon(icon1)
        self.action_Salvar = QAction(FrmDepto)
        self.action_Salvar.setObjectName(u"action_Salvar")
        icon2 = QIcon()
        icon2.addFile(u":/icones/botoes/Save.bmp", QSize(), QIcon.Normal, QIcon.Off)
        self.action_Salvar.setIcon(icon2)
        self.action_Excluir = QAction(FrmDepto)
        self.action_Excluir.setObjectName(u"action_Excluir")
        icon3 = QIcon()
        icon3.addFile(u":/icones/botoes/Minus.bmp", QSize(), QIcon.Normal, QIcon.Off)
        self.action_Excluir.setIcon(icon3)
        self.action_Cancelar = QAction(FrmDepto)
        self.action_Cancelar.setObjectName(u"action_Cancelar")
        icon4 = QIcon()
        icon4.addFile(u":/icones/botoes/REDO.BMP", QSize(), QIcon.Normal, QIcon.Off)
        self.action_Cancelar.setIcon(icon4)
        self.action_Buscar = QAction(FrmDepto)
        self.action_Buscar.setObjectName(u"action_Buscar")
        icon5 = QIcon()
        icon5.addFile(u":/icones/botoes/Oeil2.bmp", QSize(), QIcon.Normal, QIcon.Off)
        self.action_Buscar.setIcon(icon5)
        self.action_Inicio = QAction(FrmDepto)
        self.action_Inicio.setObjectName(u"action_Inicio")
        icon6 = QIcon()
        icon6.addFile(u":/icones/botoes/first.bmp", QSize(), QIcon.Normal, QIcon.Off)
        self.action_Inicio.setIcon(icon6)
        self.action_Anterior = QAction(FrmDepto)
        self.action_Anterior.setObjectName(u"action_Anterior")
        icon7 = QIcon()
        icon7.addFile(u":/icones/botoes/prior.bmp", QSize(), QIcon.Normal, QIcon.Off)
        self.action_Anterior.setIcon(icon7)
        self.action_Proximo = QAction(FrmDepto)
        self.action_Proximo.setObjectName(u"action_Proximo")
        icon8 = QIcon()
        icon8.addFile(u":/icones/botoes/next.bmp", QSize(), QIcon.Normal, QIcon.Off)
        self.action_Proximo.setIcon(icon8)
        self.action_Fim = QAction(FrmDepto)
        self.action_Fim.setObjectName(u"action_Fim")
        icon9 = QIcon()
        icon9.addFile(u":/icones/botoes/last.bmp", QSize(), QIcon.Normal, QIcon.Off)
        self.action_Fim.setIcon(icon9)
        self.action_Sair = QAction(FrmDepto)
        self.action_Sair.setObjectName(u"action_Sair")
        icon10 = QIcon()
        icon10.addFile(u":/icones/botoes/CLOSE1.BMP", QSize(), QIcon.Normal, QIcon.Off)
        self.action_Sair.setIcon(icon10)
        self.actionAgendar_consulta = QAction(FrmDepto)
        self.actionAgendar_consulta.setObjectName(u"actionAgendar_consulta")
        self.centralwidget = QWidget(FrmDepto)
        self.centralwidget.setObjectName(u"centralwidget")
        self.tabWidget = QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(0, 0, 611, 271))
        font = QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.tabWidget.setFont(font)
        self.tabWidget.setCursor(QCursor(Qt.IBeamCursor))
        self.tabCadastro = QWidget()
        self.tabCadastro.setObjectName(u"tabCadastro")
        self.label = QLabel(self.tabCadastro)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(10, 20, 221, 16))
        self.spbNumDepto = QSpinBox(self.tabCadastro)
        self.spbNumDepto.setObjectName(u"spbNumDepto")
        self.spbNumDepto.setGeometry(QRect(250, 10, 51, 31))
        self.spbNumDepto.setMinimum(1)
        self.spbNumDepto.setMaximum(25)
        self.label_2 = QLabel(self.tabCadastro)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(10, 50, 51, 21))
        self.label_3 = QLabel(self.tabCadastro)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(10, 90, 211, 21))
        self.label_4 = QLabel(self.tabCadastro)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(10, 130, 191, 31))
        self.edNomeDepto = QLineEdit(self.tabCadastro)
        self.edNomeDepto.setObjectName(u"edNomeDepto")
        self.edNomeDepto.setGeometry(QRect(250, 50, 201, 31))
        self.edNomeDepto.setMaxLength(15)
        self.edGerente_NumSegSocial = QLineEdit(self.tabCadastro)
        self.edGerente_NumSegSocial.setObjectName(u"edGerente_NumSegSocial")
        self.edGerente_NumSegSocial.setGeometry(QRect(250, 90, 131, 31))
        self.edGerente_NumSegSocial.setMaxLength(9)
        self.deData_Inicial_Gerente = QDateEdit(self.tabCadastro)
        self.deData_Inicial_Gerente.setObjectName(u"deData_Inicial_Gerente")
        self.deData_Inicial_Gerente.setGeometry(QRect(250, 130, 131, 31))
        icon11 = QIcon()
        icon11.addFile(u":/icones/COPY.BMP", QSize(), QIcon.Normal, QIcon.Off)
        self.tabWidget.addTab(self.tabCadastro, icon11, "")
        self.tabListagem = QWidget()
        self.tabListagem.setObjectName(u"tabListagem")
        self.grdDepto = QTableWidget(self.tabListagem)
        if (self.grdDepto.columnCount() < 5):
            self.grdDepto.setColumnCount(5)
        __qtablewidgetitem = QTableWidgetItem()
        self.grdDepto.setHorizontalHeaderItem(0, __qtablewidgetitem)
        __qtablewidgetitem1 = QTableWidgetItem()
        self.grdDepto.setHorizontalHeaderItem(1, __qtablewidgetitem1)
        __qtablewidgetitem2 = QTableWidgetItem()
        self.grdDepto.setHorizontalHeaderItem(2, __qtablewidgetitem2)
        __qtablewidgetitem3 = QTableWidgetItem()
        self.grdDepto.setHorizontalHeaderItem(3, __qtablewidgetitem3)
        __qtablewidgetitem4 = QTableWidgetItem()
        self.grdDepto.setHorizontalHeaderItem(4, __qtablewidgetitem4)
        self.grdDepto.setObjectName(u"grdDepto")
        self.grdDepto.setGeometry(QRect(10, 10, 591, 221))
        self.grdDepto.setFrameShadow(QFrame.Sunken)
        icon12 = QIcon()
        icon12.addFile(u":/icones/WINPREV.BMP", QSize(), QIcon.Normal, QIcon.Off)
        self.tabWidget.addTab(self.tabListagem, icon12, "")
        FrmDepto.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(FrmDepto)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 624, 21))
        self.menuCadastro = QMenu(self.menubar)
        self.menuCadastro.setObjectName(u"menuCadastro")
        self.menuListagem = QMenu(self.menubar)
        self.menuListagem.setObjectName(u"menuListagem")
        self.menuSair = QMenu(self.menubar)
        self.menuSair.setObjectName(u"menuSair")
        self.menuconsulta = QMenu(self.menubar)
        self.menuconsulta.setObjectName(u"menuconsulta")
        FrmDepto.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(FrmDepto)
        self.statusbar.setObjectName(u"statusbar")
        FrmDepto.setStatusBar(self.statusbar)
        self.tbBotoes = QToolBar(FrmDepto)
        self.tbBotoes.setObjectName(u"tbBotoes")
        self.tbBotoes.setOrientation(Qt.Horizontal)
        self.tbBotoes.setToolButtonStyle(Qt.ToolButtonTextUnderIcon)
        FrmDepto.addToolBar(Qt.TopToolBarArea, self.tbBotoes)

        self.menubar.addAction(self.menuCadastro.menuAction())
        self.menubar.addAction(self.menuListagem.menuAction())
        self.menubar.addAction(self.menuconsulta.menuAction())
        self.menubar.addAction(self.menuSair.menuAction())
        self.menuCadastro.addAction(self.actionConex_o)
        self.menuCadastro.addSeparator()
        self.menuCadastro.addAction(self.actionSair)
        self.menuListagem.addAction(self.actionListar)
        self.menuSair.addAction(self.actionSair_2)
        self.menuconsulta.addAction(self.actionAgendar_consulta)
        self.tbBotoes.addAction(self.action_Inicio)
        self.tbBotoes.addAction(self.action_Anterior)
        self.tbBotoes.addAction(self.action_Proximo)
        self.tbBotoes.addAction(self.action_Fim)
        self.tbBotoes.addSeparator()
        self.tbBotoes.addAction(self.action_Buscar)
        self.tbBotoes.addSeparator()
        self.tbBotoes.addAction(self.action_Novo)
        self.tbBotoes.addAction(self.action_Editar)
        self.tbBotoes.addAction(self.action_Salvar)
        self.tbBotoes.addSeparator()
        self.tbBotoes.addAction(self.action_Cancelar)
        self.tbBotoes.addSeparator()
        self.tbBotoes.addAction(self.action_Excluir)
        self.tbBotoes.addSeparator()
        self.tbBotoes.addAction(self.action_Sair)

        self.retranslateUi(FrmDepto)

        self.tabWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(FrmDepto)
    # setupUi

    def retranslateUi(self, FrmDepto):
        FrmDepto.setWindowTitle(QCoreApplication.translate("FrmDepto", u"Manuten\u00e7\u00e3o de Departamentos", None))
#if QT_CONFIG(tooltip)
        FrmDepto.setToolTip(QCoreApplication.translate("FrmDepto", u"Cadastro de departamentos", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        FrmDepto.setStatusTip("")
#endif // QT_CONFIG(statustip)
        self.actionConex_o.setText(QCoreApplication.translate("FrmDepto", u"Conex\u00e3o", None))
        self.actionSair.setText(QCoreApplication.translate("FrmDepto", u"Sair", None))
        self.actionListar.setText(QCoreApplication.translate("FrmDepto", u"Listar", None))
        self.actionSair_2.setText(QCoreApplication.translate("FrmDepto", u"Sair", None))
        self.action_Novo.setText(QCoreApplication.translate("FrmDepto", u"&Novo", None))
#if QT_CONFIG(tooltip)
        self.action_Novo.setToolTip(QCoreApplication.translate("FrmDepto", u"Incluir novo registro", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.action_Novo.setShortcut(QCoreApplication.translate("FrmDepto", u"Ctrl+N", None))
#endif // QT_CONFIG(shortcut)
        self.action_Editar.setText(QCoreApplication.translate("FrmDepto", u"&Editar", None))
#if QT_CONFIG(tooltip)
        self.action_Editar.setToolTip(QCoreApplication.translate("FrmDepto", u"Altera dados do registro em exibi\u00e7\u00e3o", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.action_Editar.setShortcut(QCoreApplication.translate("FrmDepto", u"Ctrl+E", None))
#endif // QT_CONFIG(shortcut)
        self.action_Salvar.setText(QCoreApplication.translate("FrmDepto", u"&Salvar", None))
#if QT_CONFIG(tooltip)
        self.action_Salvar.setToolTip(QCoreApplication.translate("FrmDepto", u"Grava o registro atual no banco de dados", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.action_Salvar.setShortcut(QCoreApplication.translate("FrmDepto", u"Ctrl+S", None))
#endif // QT_CONFIG(shortcut)
        self.action_Excluir.setText(QCoreApplication.translate("FrmDepto", u"E&xcluir", None))
#if QT_CONFIG(tooltip)
        self.action_Excluir.setToolTip(QCoreApplication.translate("FrmDepto", u"Exclui o registro exibido na tela", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.action_Excluir.setShortcut(QCoreApplication.translate("FrmDepto", u"Ctrl+X", None))
#endif // QT_CONFIG(shortcut)
        self.action_Cancelar.setText(QCoreApplication.translate("FrmDepto", u"&Cancelar", None))
#if QT_CONFIG(tooltip)
        self.action_Cancelar.setToolTip(QCoreApplication.translate("FrmDepto", u"Cancela a opera\u00e7\u00e3o atualmente em execu\u00e7\u00e3o", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.action_Cancelar.setShortcut(QCoreApplication.translate("FrmDepto", u"Ctrl+L", None))
#endif // QT_CONFIG(shortcut)
        self.action_Buscar.setText(QCoreApplication.translate("FrmDepto", u"&Buscar", None))
#if QT_CONFIG(tooltip)
        self.action_Buscar.setToolTip(QCoreApplication.translate("FrmDepto", u"Busca o registro cujo c\u00f3digo foi digitado e o exibe", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.action_Buscar.setShortcut(QCoreApplication.translate("FrmDepto", u"Ctrl+B", None))
#endif // QT_CONFIG(shortcut)
        self.action_Inicio.setText(QCoreApplication.translate("FrmDepto", u"&In\u00edcio", None))
#if QT_CONFIG(tooltip)
        self.action_Inicio.setToolTip(QCoreApplication.translate("FrmDepto", u"Posiciona visualiza\u00e7\u00e3o no primeiro registro e o exibe", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.action_Inicio.setShortcut(QCoreApplication.translate("FrmDepto", u"Ctrl+I", None))
#endif // QT_CONFIG(shortcut)
        self.action_Anterior.setText(QCoreApplication.translate("FrmDepto", u"&Anterior", None))
#if QT_CONFIG(tooltip)
        self.action_Anterior.setToolTip(QCoreApplication.translate("FrmDepto", u"Posiciona visualiza\u00e7\u00e3o no registro anterior ao atualmente exibido", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.action_Anterior.setShortcut(QCoreApplication.translate("FrmDepto", u"Ctrl+A", None))
#endif // QT_CONFIG(shortcut)
        self.action_Proximo.setText(QCoreApplication.translate("FrmDepto", u"&Pr\u00f3ximo", None))
#if QT_CONFIG(tooltip)
        self.action_Proximo.setToolTip(QCoreApplication.translate("FrmDepto", u"Posiciona visualiza\u00e7\u00e3o no registro seguinte ao atual", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.action_Proximo.setShortcut(QCoreApplication.translate("FrmDepto", u"Ctrl+P", None))
#endif // QT_CONFIG(shortcut)
        self.action_Fim.setText(QCoreApplication.translate("FrmDepto", u"&Fim", None))
#if QT_CONFIG(tooltip)
        self.action_Fim.setToolTip(QCoreApplication.translate("FrmDepto", u"Posiciona visualiza\u00e7\u00e3o no \u00faltimo registro e o exibe", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.action_Fim.setShortcut(QCoreApplication.translate("FrmDepto", u"Ctrl+F", None))
#endif // QT_CONFIG(shortcut)
        self.action_Sair.setText(QCoreApplication.translate("FrmDepto", u"Sai&r", None))
#if QT_CONFIG(tooltip)
        self.action_Sair.setToolTip(QCoreApplication.translate("FrmDepto", u"Fecha a conex\u00e3o, salva dados e fecha o formul\u00e1rio", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.action_Sair.setShortcut(QCoreApplication.translate("FrmDepto", u"Ctrl+R", None))
#endif // QT_CONFIG(shortcut)
        self.actionAgendar_consulta.setText(QCoreApplication.translate("FrmDepto", u"Agendar consulta", None))
        self.label.setText(QCoreApplication.translate("FrmDepto", u"N\u00famero do departamento:", None))
        self.label_2.setText(QCoreApplication.translate("FrmDepto", u"Nome:", None))
        self.label_3.setText(QCoreApplication.translate("FrmDepto", u"Identifica\u00e7\u00e3o do gerente:", None))
        self.label_4.setText(QCoreApplication.translate("FrmDepto", u"Data inicial do gerente:", None))
        self.edNomeDepto.setPlaceholderText(QCoreApplication.translate("FrmDepto", u"Nome do departamento", None))
        self.edGerente_NumSegSocial.setPlaceholderText(QCoreApplication.translate("FrmDepto", u"NSS do gerente", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabCadastro), QCoreApplication.translate("FrmDepto", u"Cadastro", None))
#if QT_CONFIG(tooltip)
        self.tabWidget.setTabToolTip(self.tabWidget.indexOf(self.tabCadastro), QCoreApplication.translate("FrmDepto", u"Manuten\u00e7\u00e3o dos registros de Departamentos", None))
#endif // QT_CONFIG(tooltip)
        ___qtablewidgetitem = self.grdDepto.horizontalHeaderItem(0)
        ___qtablewidgetitem.setText(QCoreApplication.translate("FrmDepto", u"N\u00fam. Depto", None));
        ___qtablewidgetitem1 = self.grdDepto.horizontalHeaderItem(1)
        ___qtablewidgetitem1.setText(QCoreApplication.translate("FrmDepto", u"Nome", None));
        ___qtablewidgetitem2 = self.grdDepto.horizontalHeaderItem(2)
        ___qtablewidgetitem2.setText(QCoreApplication.translate("FrmDepto", u"NSS Gerente", None));
        ___qtablewidgetitem3 = self.grdDepto.horizontalHeaderItem(3)
        ___qtablewidgetitem3.setText(QCoreApplication.translate("FrmDepto", u"Nome Gerente", None));
        ___qtablewidgetitem4 = self.grdDepto.horizontalHeaderItem(4)
        ___qtablewidgetitem4.setText(QCoreApplication.translate("FrmDepto", u"Data inicial", None));
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabListagem), QCoreApplication.translate("FrmDepto", u"Listagem", None))
#if QT_CONFIG(tooltip)
        self.tabWidget.setTabToolTip(self.tabWidget.indexOf(self.tabListagem), QCoreApplication.translate("FrmDepto", u"Lista os registros de Departamento", None))
#endif // QT_CONFIG(tooltip)
        self.menuCadastro.setTitle(QCoreApplication.translate("FrmDepto", u"Cadastro", None))
        self.menuListagem.setTitle(QCoreApplication.translate("FrmDepto", u"Listagem", None))
        self.menuSair.setTitle(QCoreApplication.translate("FrmDepto", u"Sair", None))
        self.menuconsulta.setTitle(QCoreApplication.translate("FrmDepto", u"Consulta", None))
        self.tbBotoes.setWindowTitle(QCoreApplication.translate("FrmDepto", u"toolBar", None))
#if QT_CONFIG(tooltip)
        self.tbBotoes.setToolTip(QCoreApplication.translate("FrmDepto", u"Bot\u00f5es de a\u00e7\u00e3o", None))
#endif // QT_CONFIG(tooltip)
    # retranslateUi

